export {default as backGround} from "./Background.jpeg"
export {default as game_1} from "./stone_paper_scissor.jpg"
export {default as stone_paper_scissor} from "./main_game_1.png"
export {default as paper} from "./paper.png"
export {default as scissor} from "./scissor.png"
export {default as stone} from "./stone.png"
export {default as game_1_side} from "./Game_1_side.png"